trigger: none

parameters:
  - name: image
    displayName: PoolImage
    default: macos-latest
    type: string
    values:
      - windows-latest
      - ubuntu-latest

stages:
  - stage: HelloWorldStage
    jobs:
    - job: build
      displayName: build
      pool: 
        vmImage: ${{ parameters.image }}
      steps:
      - script: echo building $(Build.BuildNumber) with ${{ parameters.image }}
      

  