trigger: none
pool:
  vmImage: windows-latest

stages:
  - stage: CheckoutCode
    jobs:
      - job: 'CheckoutGitCode'
        steps:
         - checkout: self
      
    jobs:
      - job: 
        steps:
          - task: Maven@4
            displayName: Maven Build
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'install'
              publishJUnitResults: false
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false

  


  







