trigger:
- main

pool:
 vmImage: 'ubuntu-latest'

stages:
  - stage: DevStage
    displayName: This is DevStage
    jobs:
      - job: DevJob
  
  - stage: QAStage
    displayName: This is QAStage
    dependsOn: DevStage
    jobs:
      - job: QAJob
  
  - stage: TestingStage
    displayName: This is TestingStage
    dependsOn: DevStage
    jobs:
      - job: TestingJob

  - stage: PreProdStage
    displayName: This is Preprod-Stage
    dependsOn: 
    - QAStage
    - TestingStage
    jobs:
      - job: PreProdJob






