trigger:
- main

pool:
 vmImage: 'ubuntu-latest'

stages:
  - stage: DevStage
    displayName: This is DevStage
    jobs:
      - job: DevJob
  
  - stage: QAStage
    displayName: This is QAStage
    dependsOn: DevStage
    jobs:
      - job: QAJob
      - task: Maven@4
        inputs:
          mavenPomFile: 'pom.xml'
          goals: 'install'
          publishJUnitResults: false
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false
  

  







