trigger:
- main

pool:
 name: ubuntu-latest

stages:
  - stage: DevStage
    displayName: This is DevStage
    jobs:
      - job: DevJob
  
  - stage: QAStage
    displayName: This is QAStage
    jobs:
      - job: QAJob

  - stage: PreProdStage
    displayName: This is Preprod-Stage
    jobs:
      - job: PreProdJob

  - stage: TestingStage
    displayName: This is TestingStage
    jobs:
      - job: TestingJob




